Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |docker|
    docker.image = "ubuntu:20.04"
    docker.has_ssh = true
    docker.remains_running = true
    docker.privileged = true
    docker.create_args = ["--cgroupns=host"]
    docker.cmd = ["/bin/bash", "-c", "while true; do sleep 3600; done"]
  end

  config.ssh.username = "root"
  config.ssh.password = "root"
  config.ssh.insert_key = false

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "forwarded_port", guest: 80, host: 8081
    server.vm.network "forwarded_port", guest: 443, host: 8444

    server.vm.provision "shell" do |s|
      s.path = "provision_server.sh"
      s.args = ["example"]
      s.privileged = true
    end
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"

    client.vm.provision "shell" do |s|
      s.path = "provision_client.sh"
      s.args = ["example"]
      s.privileged = true
    end
  end
end
