Vagrant.configure("2") do |config|
  
  config.vm.box = nil
  config.vm.box_check_update = false
  
  config.vm.define "server" do |server|
    server.vm.provider "docker" do |d|
      d.image = "ubuntu-ssh:local"
      d.name = "server-vm"
      d.has_ssh = true
      d.remains_running = true
      d.create_args = ["--hostname", "server", "--privileged"]
      d.dockerfile = "docker/Dockerfile"
    end
    
    server.vm.synced_folder "./keys", "/vagrant/keys", create: true
    server.vm.network "private_network", ip: "192.168.100.10"
    server.vm.provision "shell", path: "provision/server-setup.sh"
  end
  
  config.vm.define "client" do |client|
    client.vm.provider "docker" do |d|
      d.image = "ubuntu-ssh:local"
      d.name = "client-vm"
      d.has_ssh = true
      d.remains_running = true
      d.create_args = ["--hostname", "client", "--privileged"]
      d.dockerfile = "docker/Dockerfile"
    end
    
    client.vm.synced_folder "./keys", "/vagrant/keys", create: true
    client.vm.network "private_network", ip: "192.168.100.20"
    client.vm.provision "shell", path: "provision/client-setup.sh"
  end
  
end
